### ISSUE TITLE
pyglet.gl.lib.GLException: b'invalid operation'

### ISSUE THREAD

**Issue by jiameij** [rejuvyesh/gym-dmcontrol#1]
hi 
i run the code
```python
import gym_dmcontrol
env = gym_dmcontrol.DMControlEnv(domain='humanoid', task='run')
env.reset()
done = False
while not done:
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)  # take a random action
    env.render()
```
however it raise the problem:

Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    env.render()
  File "/home/jmj/anaconda3/lib/python3.5/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/jmj/anaconda3/lib/python3.5/site-packages/gym_dmcontrol/__init__.py", line 56, in _render
    self.viewer.update(pixels)
  File "/home/jmj/anaconda3/lib/python3.5/site-packages/gym_dmcontrol/viewer.py", line 12, in update
    self.window.clear()
  File "/home/jmj/anaconda3/lib/python3.5/site-packages/pyglet/window/__init__.py", line 1216, in clear
    gl.glClear(gl.GL_COLOR_BUFFER_BIT | gl.GL_DEPTH_BUFFER_BIT)
  File "/home/jmj/anaconda3/lib/python3.5/site-packages/pyglet/gl/lib.py", line 106, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'

how can i solve this problem?
thanks~

**Comment by jiameij** [comment]
i use python 3.5.4 and pyglet 1.3.0

**Comment by rejuvyesh** [comment]
What's your output from `python -m pyglet.info`?

**Comment by jiameij** [comment]
output:
------------------------------------------------------------------------------
sys.version: 3.5.4 |Anaconda custom (64-bit)| (default, Nov 20 2017, 18:44:38) 
[GCC 7.2.0]
sys.platform: linux
sys.maxint: 9223372036854775807
os.getcwd(): /home/jmj/anaconda3/lib/python3.5/site-packages/pyglet

pyglet
------------------------------------------------------------------------------
pyglet.version: 1.3.0
pyglet.compat_platform: linux
pyglet.__file__: /home/jmj/anaconda3/lib/python3.5/site-packages/pyglet/__init__.py
pyglet.options['font'] = ('gdiplus', 'win32')
pyglet.options['debug_gl'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_font'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_media'] = False
pyglet.options['audio'] = ('directsound', 'pulse', 'openal', 'silent')
pyglet.options['xsync'] = True
pyglet.options['debug_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['shadow_window'] = True
pyglet.options['debug_lib'] = False
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['debug_x11'] = False
pyglet.options['debug_gl_trace'] = False
pyglet.options['darwin_cocoa'] = False
pyglet.options['vsync'] = None
pyglet.options['debug_graphics_batch'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_texture'] = False
pyglet.options['graphics_vbo'] = True

pyglet.window
------------------------------------------------------------------------------
platform: <pyglet.window.Platform object at 0x7fba06980a20>
display: <pyglet.canvas.xlib.XlibDisplay object at 0x7fba06130da0>
screens[0]: XlibScreen(display=<pyglet.canvas.xlib.XlibDisplay object at 0x7fba06130da0>, x=0, y=0, width=1920, height=1080, xinerama=0)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 24
config['aux_buffers'] = 4
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 0
config['depth_size'] = 24
config['stencil_size'] = 0
config['accum_red_size'] = 16
config['accum_green_size'] = 16
config['accum_blue_size'] = 16
config['accum_alpha_size'] = 16
config['major_version'] = None
config['minor_version'] = None
config['forward_compatible'] = None
config['debug'] = None
context: XlibContextARB()

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): 4.5.0 NVIDIA 384.111
gl_info.get_vendor(): NVIDIA Corporation
gl_info.get_renderer(): GeForce GT 710/PCIe/SSE2
gl_info.get_extensions():
   GL_AMD_multi_draw_indirect
   GL_AMD_seamless_cubemap_per_texture
   GL_ARB_ES2_compatibility
   GL_ARB_ES3_1_compatibility
   GL_ARB_ES3_2_compatibility
   GL_ARB_ES3_compatibility
   GL_ARB_arrays_of_arrays
   GL_ARB_base_instance
   GL_ARB_bindless_texture
   GL_ARB_blend_func_extended
   GL_ARB_buffer_storage
   GL_ARB_clear_buffer_object
   GL_ARB_clear_texture
   GL_ARB_clip_control
   GL_ARB_color_buffer_float
   GL_ARB_compatibility
   GL_ARB_compressed_texture_pixel_storage
   GL_ARB_compute_shader
   GL_ARB_compute_variable_group_size
   GL_ARB_conditional_render_inverted
   GL_ARB_conservative_depth
   GL_ARB_copy_buffer
   GL_ARB_copy_image
   GL_ARB_cull_distance
   GL_ARB_debug_output
   GL_ARB_depth_buffer_float
   GL_ARB_depth_clamp
   GL_ARB_depth_texture
   GL_ARB_derivative_control
   GL_ARB_direct_state_access
   GL_ARB_draw_buffers
   GL_ARB_draw_buffers_blend
   GL_ARB_draw_elements_base_vertex
   GL_ARB_draw_indirect
   GL_ARB_draw_instanced
   GL_ARB_enhanced_layouts
   GL_ARB_explicit_attrib_location
   GL_ARB_explicit_uniform_location
   GL_ARB_fragment_coord_conventions
   GL_ARB_fragment_layer_viewport
   GL_ARB_fragment_program
   GL_ARB_fragment_program_shadow
   GL_ARB_fragment_shader
   GL_ARB_framebuffer_no_attachments
   GL_ARB_framebuffer_object
   GL_ARB_framebuffer_sRGB
   GL_ARB_geometry_shader4
   GL_ARB_get_program_binary
   GL_ARB_get_texture_sub_image
   GL_ARB_gl_spirv
   GL_ARB_gpu_shader5
   GL_ARB_gpu_shader_fp64
   GL_ARB_gpu_shader_int64
   GL_ARB_half_float_pixel
   GL_ARB_half_float_vertex
   GL_ARB_imaging
   GL_ARB_indirect_parameters
   GL_ARB_instanced_arrays
   GL_ARB_internalformat_query
   GL_ARB_internalformat_query2
   GL_ARB_invalidate_subdata
   GL_ARB_map_buffer_alignment
   GL_ARB_map_buffer_range
   GL_ARB_multi_bind
   GL_ARB_multi_draw_indirect
   GL_ARB_multisample
   GL_ARB_multitexture
   GL_ARB_occlusion_query
   GL_ARB_occlusion_query2
   GL_ARB_parallel_shader_compile
   GL_ARB_pipeline_statistics_query
   GL_ARB_pixel_buffer_object
   GL_ARB_point_parameters
   GL_ARB_point_sprite
   GL_ARB_program_interface_query
   GL_ARB_provoking_vertex
   GL_ARB_query_buffer_object
   GL_ARB_robust_buffer_access_behavior
   GL_ARB_robustness
   GL_ARB_sample_shading
   GL_ARB_sampler_objects
   GL_ARB_seamless_cube_map
   GL_ARB_seamless_cubemap_per_texture
   GL_ARB_separate_shader_objects
   GL_ARB_shader_atomic_counter_ops
   GL_ARB_shader_atomic_counters
   GL_ARB_shader_ballot
   GL_ARB_shader_bit_encoding
   GL_ARB_shader_clock
   GL_ARB_shader_draw_parameters
   GL_ARB_shader_group_vote
   GL_ARB_shader_image_load_store
   GL_ARB_shader_image_size
   GL_ARB_shader_objects
   GL_ARB_shader_precision
   GL_ARB_shader_storage_buffer_object
   GL_ARB_shader_subroutine
   GL_ARB_shader_texture_image_samples
   GL_ARB_shader_texture_lod
   GL_ARB_shading_language_100
   GL_ARB_shading_language_420pack
   GL_ARB_shading_language_include
   GL_ARB_shading_language_packing
   GL_ARB_shadow
   GL_ARB_sparse_buffer
   GL_ARB_sparse_texture
   GL_ARB_stencil_texturing
   GL_ARB_sync
   GL_ARB_tessellation_shader
   GL_ARB_texture_barrier
   GL_ARB_texture_border_clamp
   GL_ARB_texture_buffer_object
   GL_ARB_texture_buffer_object_rgb32
   GL_ARB_texture_buffer_range
   GL_ARB_texture_compression
   GL_ARB_texture_compression_bptc
   GL_ARB_texture_compression_rgtc
   GL_ARB_texture_cube_map
   GL_ARB_texture_cube_map_array
   GL_ARB_texture_env_add
   GL_ARB_texture_env_combine
   GL_ARB_texture_env_crossbar
   GL_ARB_texture_env_dot3
   GL_ARB_texture_float
   GL_ARB_texture_gather
   GL_ARB_texture_mirror_clamp_to_edge
   GL_ARB_texture_mirrored_repeat
   GL_ARB_texture_multisample
   GL_ARB_texture_non_power_of_two
   GL_ARB_texture_query_levels
   GL_ARB_texture_query_lod
   GL_ARB_texture_rectangle
   GL_ARB_texture_rg
   GL_ARB_texture_rgb10_a2ui
   GL_ARB_texture_stencil8
   GL_ARB_texture_storage
   GL_ARB_texture_storage_multisample
   GL_ARB_texture_swizzle
   GL_ARB_texture_view
   GL_ARB_timer_query
   GL_ARB_transform_feedback2
   GL_ARB_transform_feedback3
   GL_ARB_transform_feedback_instanced
   GL_ARB_transform_feedback_overflow_query
   GL_ARB_transpose_matrix
   GL_ARB_uniform_buffer_object
   GL_ARB_vertex_array_bgra
   GL_ARB_vertex_array_object
   GL_ARB_vertex_attrib_64bit
   GL_ARB_vertex_attrib_binding
   GL_ARB_vertex_buffer_object
   GL_ARB_vertex_program
   GL_ARB_vertex_shader
   GL_ARB_vertex_type_10f_11f_11f_rev
   GL_ARB_vertex_type_2_10_10_10_rev
   GL_ARB_viewport_array
   GL_ARB_window_pos
   GL_ATI_draw_buffers
   GL_ATI_texture_float
   GL_ATI_texture_mirror_once
   GL_EXTX_framebuffer_mixed_formats
   GL_EXT_Cg_shader
   GL_EXT_abgr
   GL_EXT_bgra
   GL_EXT_bindable_uniform
   GL_EXT_blend_color
   GL_EXT_blend_equation_separate
   GL_EXT_blend_func_separate
   GL_EXT_blend_minmax
   GL_EXT_blend_subtract
   GL_EXT_compiled_vertex_array
   GL_EXT_depth_bounds_test
   GL_EXT_direct_state_access
   GL_EXT_draw_buffers2
   GL_EXT_draw_instanced
   GL_EXT_draw_range_elements
   GL_EXT_fog_coord
   GL_EXT_framebuffer_blit
   GL_EXT_framebuffer_multisample
   GL_EXT_framebuffer_multisample_blit_scaled
   GL_EXT_framebuffer_object
   GL_EXT_framebuffer_sRGB
   GL_EXT_geometry_shader4
   GL_EXT_gpu_program_parameters
   GL_EXT_gpu_shader4
   GL_EXT_import_sync_object
   GL_EXT_memory_object
   GL_EXT_memory_object_fd
   GL_EXT_multi_draw_arrays
   GL_EXT_packed_depth_stencil
   GL_EXT_packed_float
   GL_EXT_packed_pixels
   GL_EXT_pixel_buffer_object
   GL_EXT_point_parameters
   GL_EXT_polygon_offset_clamp
   GL_EXT_provoking_vertex
   GL_EXT_rescale_normal
   GL_EXT_secondary_color
   GL_EXT_semaphore
   GL_EXT_semaphore_fd
   GL_EXT_separate_shader_objects
   GL_EXT_separate_specular_color
   GL_EXT_shader_image_load_store
   GL_EXT_shader_integer_mix
   GL_EXT_shadow_funcs
   GL_EXT_stencil_two_side
   GL_EXT_stencil_wrap
   GL_EXT_texture3D
   GL_EXT_texture_array
   GL_EXT_texture_buffer_object
   GL_EXT_texture_compression_dxt1
   GL_EXT_texture_compression_latc
   GL_EXT_texture_compression_rgtc
   GL_EXT_texture_compression_s3tc
   GL_EXT_texture_cube_map
   GL_EXT_texture_edge_clamp
   GL_EXT_texture_env_add
   GL_EXT_texture_env_combine
   GL_EXT_texture_env_dot3
   GL_EXT_texture_filter_anisotropic
   GL_EXT_texture_integer
   GL_EXT_texture_lod
   GL_EXT_texture_lod_bias
   GL_EXT_texture_mirror_clamp
   GL_EXT_texture_object
   GL_EXT_texture_sRGB
   GL_EXT_texture_sRGB_decode
   GL_EXT_texture_shared_exponent
   GL_EXT_texture_storage
   GL_EXT_texture_swizzle
   GL_EXT_timer_query
   GL_EXT_transform_feedback2
   GL_EXT_vertex_array
   GL_EXT_vertex_array_bgra
   GL_EXT_vertex_attrib_64bit
   GL_EXT_window_rectangles
   GL_EXT_x11_sync_object
   GL_IBM_rasterpos_clip
   GL_IBM_texture_mirrored_repeat
   GL_KHR_blend_equation_advanced
   GL_KHR_context_flush_control
   GL_KHR_debug
   GL_KHR_no_error
   GL_KHR_robust_buffer_access_behavior
   GL_KHR_robustness
   GL_KTX_buffer_region
   GL_NVX_conditional_render
   GL_NVX_gpu_memory_info
   GL_NVX_nvenc_interop
   GL_NV_ES1_1_compatibility
   GL_NV_ES3_1_compatibility
   GL_NV_alpha_to_coverage_dither_control
   GL_NV_bindless_multi_draw_indirect
   GL_NV_bindless_multi_draw_indirect_count
   GL_NV_bindless_texture
   GL_NV_blend_equation_advanced
   GL_NV_blend_square
   GL_NV_command_list
   GL_NV_compute_program5
   GL_NV_conditional_render
   GL_NV_copy_depth_to_color
   GL_NV_copy_image
   GL_NV_depth_buffer_float
   GL_NV_depth_clamp
   GL_NV_draw_texture
   GL_NV_draw_vulkan_image
   GL_NV_explicit_multisample
   GL_NV_fence
   GL_NV_float_buffer
   GL_NV_fog_distance
   GL_NV_fragment_program
   GL_NV_fragment_program2
   GL_NV_fragment_program_option
   GL_NV_framebuffer_multisample_coverage
   GL_NV_geometry_shader4
   GL_NV_gpu_program4
   GL_NV_gpu_program4_1
   GL_NV_gpu_program5
   GL_NV_gpu_program5_mem_extended
   GL_NV_gpu_program_fp64
   GL_NV_gpu_shader5
   GL_NV_half_float
   GL_NV_internalformat_sample_query
   GL_NV_light_max_exponent
   GL_NV_multisample_coverage
   GL_NV_multisample_filter_hint
   GL_NV_occlusion_query
   GL_NV_packed_depth_stencil
   GL_NV_parameter_buffer_object
   GL_NV_parameter_buffer_object2
   GL_NV_path_rendering
   GL_NV_pixel_data_range
   GL_NV_point_sprite
   GL_NV_primitive_restart
   GL_NV_register_combiners
   GL_NV_register_combiners2
   GL_NV_robustness_video_memory_purge
   GL_NV_shader_atomic_counters
   GL_NV_shader_atomic_float
   GL_NV_shader_atomic_int64
   GL_NV_shader_buffer_load
   GL_NV_shader_storage_buffer_object
   GL_NV_shader_thread_group
   GL_NV_shader_thread_shuffle
   GL_NV_texgen_reflection
   GL_NV_texture_barrier
   GL_NV_texture_compression_vtc
   GL_NV_texture_env_combine4
   GL_NV_texture_multisample
   GL_NV_texture_rectangle
   GL_NV_texture_shader
   GL_NV_texture_shader2
   GL_NV_texture_shader3
   GL_NV_transform_feedback
   GL_NV_transform_feedback2
   GL_NV_uniform_buffer_unified_memory
   GL_NV_vdpau_interop
   GL_NV_vertex_array_range
   GL_NV_vertex_array_range2
   GL_NV_vertex_attrib_integer_64bit
   GL_NV_vertex_buffer_unified_memory
   GL_NV_vertex_program
   GL_NV_vertex_program1_1
   GL_NV_vertex_program2
   GL_NV_vertex_program2_option
   GL_NV_vertex_program3
   GL_S3_s3tc
   GL_SGIS_generate_mipmap
   GL_SGIS_texture_lod
   GL_SGIX_depth_texture
   GL_SGIX_shadow
   GL_SUN_slice_accum

pyglet.gl.glu_info
------------------------------------------------------------------------------
glu_info.get_version(): 1.3
glu_info.get_extensions():
   GLU_EXT_nurbs_tessellator
   GLU_EXT_object_space_tess

pyglet.gl.glx_info
------------------------------------------------------------------------------
context.is_direct(): 1
glx_info.get_server_vendor(): NVIDIA Corporation
glx_info.get_server_version(): 1.4
glx_info.get_server_extensions():
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_EXT_import_context
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGI_video_sync
   GLX_SGI_swap_control
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_texture_from_pixmap
   GLX_EXT_buffer_age
   GLX_ARB_create_context
   GLX_ARB_create_context_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_create_context_es2_profile
   GLX_ARB_create_context_robustness
   GLX_NV_delay_before_swap
   GLX_EXT_stereo_tree
   GLX_EXT_libglvnd
   GLX_ARB_context_flush_control
   GLX_NV_robustness_video_memory_purge
   GLX_ARB_multisample
   GLX_NV_float_buffer
   GLX_ARB_fbconfig_float
   GLX_EXT_framebuffer_sRGB
   GLX_NV_multisample_coverage
   GLX_NV_copy_image
glx_info.get_client_vendor(): NVIDIA Corporation
glx_info.get_client_version(): 1.4
glx_info.get_client_extensions():
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_EXT_import_context
   GLX_SGI_video_sync
   GLX_NV_swap_group
   GLX_NV_video_out
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGI_swap_control
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_buffer_age
   GLX_ARB_create_context
   GLX_ARB_create_context_profile
   GLX_NV_float_buffer
   GLX_ARB_fbconfig_float
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_texture_from_pixmap
   GLX_EXT_framebuffer_sRGB
   GLX_NV_present_video
   GLX_NV_copy_image
   GLX_NV_copy_buffer
   GLX_NV_multisample_coverage
   GLX_NV_video_capture
   GLX_EXT_create_context_es_profile
   GLX_EXT_create_context_es2_profile
   GLX_ARB_create_context_robustness
   GLX_NV_delay_before_swap
   GLX_EXT_stereo_tree
   GLX_ARB_context_flush_control
   GLX_NV_robustness_video_memory_purge
glx_info.get_extensions():
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_EXT_import_context
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGI_video_sync
   GLX_SGI_swap_control
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_texture_from_pixmap
   GLX_EXT_buffer_age
   GLX_ARB_create_context
   GLX_ARB_create_context_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_create_context_es2_profile
   GLX_ARB_create_context_robustness
   GLX_NV_delay_before_swap
   GLX_EXT_stereo_tree
   GLX_ARB_context_flush_control
   GLX_NV_robustness_video_memory_purge
   GLX_ARB_multisample
   GLX_NV_float_buffer
   GLX_ARB_fbconfig_float
   GLX_EXT_framebuffer_sRGB
   GLX_NV_multisample_coverage
   GLX_NV_copy_image
   GLX_ARB_get_proc_address

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.pulse.adaptation.PulseAudioDriver object at 0x7fb9ff7e0630>

pyglet.media.avbin
------------------------------------------------------------------------------
AVbin not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'libopenal.so.1', handle 55e103387350 at 0x7fba03b9e240>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_DEDICATED
   ALC_EXT_disconnect
   ALC_EXT_EFX
   ALC_EXT_thread_local_context
   ALC_SOFTX_device_clock
   ALC_SOFTX_HRTF
   ALC_SOFT_loopback
   ALC_SOFTX_midi_interface
   ALC_SOFT_pause_device

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.

i use:
sudo apt-get install freeglut3-dev
now it can only show one image, others are all black
and when i run the demo:
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
how can i solve this problem?
thank you very much!

**Comment by jiameij** [comment]
in the second frame,which first become black 
dm_control/mujoco.engine.py --render() after 
mjlib.mjr_render(self._rect, self._scene.ptr,
                       self._physics.contexts.mujoco.ptr)
raise gl.glGetError()=1282 error
and 
mjlib.mjr_readPixels(self._rgb_buffer, None, self._rect,
                             self._physics.contexts.mujoco.ptr)
change self._rgb_buffer to  all 0
thank you!

**Comment by rejuvyesh** [comment]
There's some issue with Nvidia OpenGL. Works fine on the `mesa` one.

**Comment by jiameij** [comment]
i install Mesa by ppa:
 sudo add-apt-repository ppa:ubuntu-x-swat/updates
 sudo apt update && sudo apt dist-upgrade
then update the system
finally i run: glxinfo | grep "OpenGL version"
it shows that:
OpenGL version string: 3.0 Mesa 17.3.3
however, it can not solve this problem
is there something wrong ?
thank you very much!

**Comment by rejuvyesh** [comment]
Does the current version help?

**Comment by jiameij** [comment]
the current version is 17.3.3, i installed it by ppa. maybe i should install it by source code. thank you very much for your help.

**Comment by rejuvyesh** [comment]
I meant that I made a few changes to mitigate the problem. Wanted to check if that helps.

**Comment by jiameij** [comment]
the current version can not solve this problem. Thanks ~

**Comment by justmichaelwang** [comment]
having the same issue. Would anyone be so kind to help me please?

Here is the error:
Traceback (most recent call last):
  File "Video_06_transformations_scaling/Window4.py", line 25, in <module>
    window = MyWindow(1280, 720, "My Pyglet Window", resizable=True)
  File "Video_06_transformations_scaling/Window4.py", line 10, in __init__
    self.triangle = Triangle()
  File "/Users/mwang/Desktop/HappyHackers/re/Pyglet_OpenGL_tutorials/Video_06_transformations_scaling/Triangle4.py", line 58, in __init__
    glUseProgram(shader)
  File "/Users/mwang/.local/lib/python3.6/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'

Here is some info:
Python
------------------------------------------------------------------------------
sys.version: 3.5.4 |Anaconda custom (x86_64)| (default, Sep 21 2017, 18:03:17) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
sys.platform: darwin
sys.maxint: 9223372036854775807
PyObjC not available
os.getcwd(): /Users/mwang/Desktop/HappyHackers/re/Pyglet_OpenGL_tutorials

pyglet
------------------------------------------------------------------------------
pyglet.version: 1.3.1
pyglet.compat_platform: darwin
pyglet.__file__: /Users/mwang/.local/lib/python3.6/site-packages/pyglet/__init__.py
pyglet.options['debug_font'] = False
pyglet.options['shadow_window'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_trace'] = False
pyglet.options['audio'] = ('directsound', 'pulse', 'openal', 'silent')
pyglet.options['graphics_vbo'] = True
pyglet.options['vsync'] = None
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace_flush'] = True
pyglet.options['search_local_libs'] = True
pyglet.options['darwin_cocoa'] = True
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_lib'] = False
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_win32'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['xsync'] = True
pyglet.options['font'] = ('gdiplus', 'win32')
pyglet.options['debug_gl'] = True
pyglet.options['debug_x11'] = False

pyglet.window
------------------------------------------------------------------------------
platform: <pyglet.window.Platform object at 0x10adb3470>
display: <pyglet.canvas.cocoa.CocoaDisplay object at 0x10b081780>
screens[0]: CocoaScreen(x=0, y=0, width=1440, height=900)
screens[1]: CocoaScreen(x=-1920, y=0, width=1920, height=1080)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 32
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 0
config['green_size'] = 0
config['blue_size'] = 0
config['alpha_size'] = 8
config['depth_size'] = 24
config['stencil_size'] = 0
config['accum_red_size'] = 0
config['accum_green_size'] = 0
config['accum_blue_size'] = 0
config['accum_alpha_size'] = 0
config['major_version'] = 2
config['minor_version'] = 1
config['forward_compatible'] = None
config['debug'] = None
context: CocoaContext()

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): 2.1 INTEL-10.12.13
gl_info.get_vendor(): Intel Inc.
gl_info.get_renderer(): Intel Iris Pro OpenGL Engine
gl_info.get_extensions():
   GL_APPLE_aux_depth_stencil
   GL_APPLE_client_storage
   GL_APPLE_element_array
   GL_APPLE_fence
   GL_APPLE_float_pixels
   GL_APPLE_flush_buffer_range
   GL_APPLE_flush_render
   GL_APPLE_object_purgeable
   GL_APPLE_packed_pixels
   GL_APPLE_pixel_buffer
   GL_APPLE_rgb_422
   GL_APPLE_row_bytes
   GL_APPLE_specular_vector
   GL_APPLE_texture_range
   GL_APPLE_transform_hint
   GL_APPLE_vertex_array_object
   GL_APPLE_vertex_array_range
   GL_APPLE_vertex_point_size
   GL_APPLE_vertex_program_evaluators
   GL_APPLE_ycbcr_422
   GL_ARB_color_buffer_float
   GL_ARB_depth_buffer_float
   GL_ARB_depth_clamp
   GL_ARB_depth_texture
   GL_ARB_draw_buffers
   GL_ARB_draw_elements_base_vertex
   GL_ARB_draw_instanced
   GL_ARB_fragment_program
   GL_ARB_fragment_program_shadow
   GL_ARB_fragment_shader
   GL_ARB_framebuffer_object
   GL_ARB_framebuffer_sRGB
   GL_ARB_half_float_pixel
   GL_ARB_half_float_vertex
   GL_ARB_instanced_arrays
   GL_ARB_multisample
   GL_ARB_multitexture
   GL_ARB_occlusion_query
   GL_ARB_pixel_buffer_object
   GL_ARB_point_parameters
   GL_ARB_point_sprite
   GL_ARB_provoking_vertex
   GL_ARB_seamless_cube_map
   GL_ARB_shader_objects
   GL_ARB_shader_texture_lod
   GL_ARB_shading_language_100
   GL_ARB_shadow
   GL_ARB_sync
   GL_ARB_texture_border_clamp
   GL_ARB_texture_compression
   GL_ARB_texture_compression_rgtc
   GL_ARB_texture_cube_map
   GL_ARB_texture_env_add
   GL_ARB_texture_env_combine
   GL_ARB_texture_env_crossbar
   GL_ARB_texture_env_dot3
   GL_ARB_texture_float
   GL_ARB_texture_mirrored_repeat
   GL_ARB_texture_non_power_of_two
   GL_ARB_texture_rectangle
   GL_ARB_texture_rg
   GL_ARB_transpose_matrix
   GL_ARB_vertex_array_bgra
   GL_ARB_vertex_blend
   GL_ARB_vertex_buffer_object
   GL_ARB_vertex_program
   GL_ARB_vertex_shader
   GL_ARB_window_pos
   GL_ATI_separate_stencil
   GL_ATI_texture_env_combine3
   GL_ATI_texture_float
   GL_ATI_texture_mirror_once
   GL_EXT_abgr
   GL_EXT_bgra
   GL_EXT_blend_color
   GL_EXT_blend_equation_separate
   GL_EXT_blend_func_separate
   GL_EXT_blend_minmax
   GL_EXT_blend_subtract
   GL_EXT_clip_volume_hint
   GL_EXT_debug_label
   GL_EXT_debug_marker
   GL_EXT_draw_buffers2
   GL_EXT_draw_range_elements
   GL_EXT_fog_coord
   GL_EXT_framebuffer_blit
   GL_EXT_framebuffer_multisample
   GL_EXT_framebuffer_multisample_blit_scaled
   GL_EXT_framebuffer_object
   GL_EXT_framebuffer_sRGB
   GL_EXT_geometry_shader4
   GL_EXT_gpu_program_parameters
   GL_EXT_gpu_shader4
   GL_EXT_multi_draw_arrays
   GL_EXT_packed_depth_stencil
   GL_EXT_packed_float
   GL_EXT_provoking_vertex
   GL_EXT_rescale_normal
   GL_EXT_secondary_color
   GL_EXT_separate_specular_color
   GL_EXT_shadow_funcs
   GL_EXT_stencil_two_side
   GL_EXT_stencil_wrap
   GL_EXT_texture_array
   GL_EXT_texture_compression_dxt1
   GL_EXT_texture_compression_s3tc
   GL_EXT_texture_env_add
   GL_EXT_texture_filter_anisotropic
   GL_EXT_texture_integer
   GL_EXT_texture_lod_bias
   GL_EXT_texture_rectangle
   GL_EXT_texture_sRGB
   GL_EXT_texture_sRGB_decode
   GL_EXT_texture_shared_exponent
   GL_EXT_timer_query
   GL_EXT_transform_feedback
   GL_EXT_vertex_array_bgra
   GL_IBM_rasterpos_clip
   GL_NV_blend_square
   GL_NV_conditional_render
   GL_NV_depth_clamp
   GL_NV_fog_distance
   GL_NV_light_max_exponent
   GL_NV_texgen_reflection
   GL_NV_texture_barrier
   GL_SGIS_generate_mipmap
   GL_SGIS_texture_edge_clamp
   GL_SGIS_texture_lod

pyglet.gl.glu_info
------------------------------------------------------------------------------
glu_info.get_version(): 1.3 MacOSX
glu_info.get_extensions():

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.openal.adaptation.OpenALDriver object at 0x10c580198>

pyglet.media.avbin
------------------------------------------------------------------------------
AVbin not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL '/System/Library/Frameworks/OpenAL.framework/OpenAL', handle 7ff1bdd63d10 at 0x10c798dd8>
Version: 1.1
Extensions:
   ALC_EXT_CAPTURE
   ALC_ENUMERATION_EXT
   ALC_EXT_MAC_OSX
   ALC_EXT_ASA
   ALC_EXT_ASA_DISTORTION
   ALC_EXT_ASA_ROGER_BEEP

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.

**Comment by yosider** [comment]
See https://github.com/martinseilair/dm_control2gym/issues/2
